### ISSUE TITLE
Group theory 

### ISSUE THREAD

**Issue by aronwalsh** [bjmorgan/bsym#3]
As I understand there is no internal library of point group operations or character tables included. Could these be imported from spglib?

**Comment by bjmorgan** [comment]
@aronwalsh It isn't clear why this would be useful. Can you provide an example use case?

**Comment by aronwalsh** [comment]
I had the lazy user in mind, for faster application to chemical problems. The ability to call a set of predefined symmetry operations instead of having to define them.

**Comment by bjmorgan** [comment]
If the system is described by a `pymatgen` `Structure` object, you can generate the `bsym` `SpaceGroup` using `bsym.interface.spacegroup_from_structure()`.

http://bsym.readthedocs.io/en/latest/api/interface/pymatgen.html#bsym.interface.pymatgen.spacegroup_from_structure

```python
def spacegroup_from_structure( structure, subset=None ):
    """
    Generates a ``SpaceGroup`` object from a `pymatgen` ``Structure``. 

    Args:
        structure (pymatgen ``Structure``): structure to be used to define the :any:`SpaceGroup`.
        subset    (Optional [list]):        list of atom indices to be used for generating the symmetry operations.

    Returns:
        a new :any:`SpaceGroup` instance
    """
```

The design choice to use the `pymatgen` API, rather than reimplement a direct interface with `spglib`, was, in part, motivated by the excellent support in `pymatgen` for converting between multiple standard structure file and data formats, and the expectation that most users would prefer to work with structures in a "standard" format, rather than having to generate a `bsym` structure object.

**Comment by bjmorgan** [comment]
For better discoverability, I have added examples of the `spacegroup_from_structure()` and `configuration_space_from_structure()` functions from `bsym.interface.pymatgen` to the example Jupyter notebook. 

relevant commit: d05267b3aaee857bd99e1febff7268a348610e4e
